language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t swither/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swither/react-test npm test -- --coverage

after_success:
  - docker build -t swither/complex-client ./client
  - docker build -t swither/complex-nginx ./nginx
  - docker build -t swither/complex-server ./server
  - docker build -t swither/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push swither/complex-client
  - docker push swither/complex-nginx
  - docker push swither/complex-server
  - docker push swither/complex-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "complex-docker"
  env: "ComplexDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-882925408877"
  bucket_path: "complex-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
